CUDA_VISIBLE_DEVICES=6 python train.py \
--dataset kitti \
--data_path /home/share/datasets/kitti/raw_data_sync \
--log_dir checkpoints_kitti \
--split eigen_zhou \
--min_depth 1e-3 --max_depth 100 \
--height 256 --width 832 \
--frame_ids 0 -1 1 \
--log_frequency 100 \
--png \
--scales 0 \
--geometry_consistency 0.1 \
--model_name kitti-g0.1